{% raw -%}
name: Publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Build
      run: |
        python setup.py bdist_wheel --python-tag py3
    - name: Packagr Publish
      env:
        TWINE_USERNAME: ""
        TWINE_PASSWORD: ${{ secrets.PACKAGR_TOKEN }}
        URL: ${{ secrets.PACKAGR_URL }}
      run:
        twine upload dist/* --repository-url https://api.packagr.app/${URL}/
{%- endraw %}
